// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKToaX_AGnXWi-VQGAleLBWL_znRm6gq4',
    appId: '1:541073163713:web:583c37c4809f68934a9b40',
    messagingSenderId: '541073163713',
    projectId: 'isid-push-notification-6dad3',
    authDomain: 'isid-push-notification-6dad3.firebaseapp.com',
    storageBucket: 'isid-push-notification-6dad3.appspot.com',
    measurementId: 'G-B278QMB1N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_WuDrImIHLSn6RoLj5UsH1BBz8rVE10',
    appId: '1:541073163713:android:a3fa59292e08a5684a9b40',
    messagingSenderId: '541073163713',
    projectId: 'isid-push-notification-6dad3',
    storageBucket: 'isid-push-notification-6dad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiuqekem4j8IXdR5MSr5P1_buo0CvC3U',
    appId: '1:541073163713:ios:9e24f1cd26b9371f4a9b40',
    messagingSenderId: '541073163713',
    projectId: 'isid-push-notification-6dad3',
    storageBucket: 'isid-push-notification-6dad3.appspot.com',
    iosClientId:
        '541073163713-4s8122u6eulmgu3is3r5pcev7q1hlomi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleCodeIsid',
  );
}
